version: "3.8"
volumes:
    postgres_data:
    nginx_conf:
    media:
    static:
services:
  db:
    image: postgres:12.4
    volumes:
        - postgres_data:/var/lib/postgresql/data/
    env_file:
        - ./.env
  web:
    image: gilions/yamdb
    restart: always
    volumes:
        - media:/code/media
        - nginx_conf:/code/nginx/
        - static:/code/static
    depends_on:
        - db
    env_file:
        - ./.env
  nginx:
    image: nginx:1.19.7-alpine
    volumes:
        - static:/code/static
        - media:/code/media
        - nginx_conf:/etc/nginx/conf.d/
    restart: always
    ports:
        - "80:80"
    depends_on:
        - web
