name: yamdb workflow

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r requirements.txt
    - name: Lint with flake8
      run: flake8 .

  build_and_push_to_docker_hub:
    name: Run Docker images
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Setings SSH remote
        uses: kielabokkie/ssh-key-and-known-hosts-action@v1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-host: ${{ secrets.SSH_HOST }}
        run: |
          sudo pip install docker-compose
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          docker context create remote --docker "host=ssh://gilion@${{ secrets.SSH_HOST }}"
          docker context use remote
          docker-compose --context remote up -d --force-recreate